apiVersion: v1
kind: Service
metadata:
  name: wordpress-svc
spec:
  selector:
    app: wordpress
    tier: frontend
  type: NodePort
  ports:                           
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30020